### ISSUE TITLE
Profile error

### ISSUE THREAD

**Issue by alexbagirov** [MoarCatz/chat-client#28]
### Error Text
```
Traceback (most recent call last):
   File "Chat_UI.py", line 2887, in <module>
     app.run()
   File "/usr/lib/python3/dist-packages/kivy/app.py", line 828, in run
     runTouchApp()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 500, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 637, in mainloop
     self._mainloop()
   File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 390, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 339, in idle
     self.dispatch_input()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 324, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 290, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
   File "/usr/lib/python3/dist-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7681)
   File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy/_event.c:13524)
   File "kivy/_event.pyx", line 1149, in kivy._event.EventObservers._dispatch (kivy/_event.c:13050)
   File "Chat_UI.py", line 2549, in to_self_profile
     self.self_profile_scr.set_up_for(self.nick)
   File "Chat_UI.py", line 726, in set_up_for
     page.email_field.text = profile_data.email
   File "kivy/properties.pyx", line 423, in kivy.properties.Property.__set__ (kivy/properties.c:5171)
   File "kivy/properties.pyx", line 1416, in kivy.properties.AliasProperty.set (kivy/properties.c:23280)
   File "/usr/lib/python3/dist-packages/kivy/uix/textinput.py", line 2918, in _set_text
     text = text.replace(u'\r\n', u'\n')
 AttributeError: 'int' object has no attribute 'replace'
```

### Steps To Reproduce

1. Log in with your account
2. Hit the **Profile button**

**Comment by alexbagirov** [comment]
Closed in https://github.com/MoarCatz/chat-client/commit/d61da07dae2114d91717f904d3ebee3d66547751.
